/*package random;

public class exceptionHandling {

	public static void main(String[] args) {
		 int a=0,b=10;
		 System.out.println("Before division by zero b equal to "+b);
		 
		try {
			b=b/a;
			System.exit(0); //program doesnt exit here because it found exception in try block so catch block is executed
		} catch (Exception e) {
			System.out.println("Exception is "+ e);
			System.exit(0);
		} 
		System.out.println("value of b after catching exception"+ b);
		
	}

}*/
